### PR TITLE
Replace IE logo with Edge

### PR DESCRIPTION
**Pull request by patrickkettner**
I thought it might be better to show the Edge logo rather than IE's, as the later is dead nowadays

### CODE REVIEW

**Comment by garrows** [comment]
Nice one @patrickkettner. Thank you.

**Comment by garrows** [comment]
@iamkevinv you might want to update your slides.

**Comment by AshKyd** [comment]
Looks like this might have been resized by accident as the stroke has changed on the Firefox logo, doesn't look great. Could we get another version with the stroke fixed please?

*Original*:


*This PR*:

**Comment by patrickkettner** [comment]
Happy to try again, what tool was used to create this in the first place? I just exported with default settings in illustrator so I'm not sure what the cause of that would have been other than tool incompatibilities

**Comment by AshKyd** [comment]
It was authored in Inkscape, but I don't think that should matter per se. If it would help I can try to output a flattened version with no strokes.

**Pull request merged**
